FROM golang:1.26-alpine AS builder
WORKDIR /build

COPY common/   ./common/
COPY database/ ./database/
COPY locale/   ./locale/
COPY gateway/  ./gateway/

WORKDIR /build/gateway
RUN sed -i 's|// replace github.com/PurgeBot-net/|replace github.com/PurgeBot-net/|g' go.mod
RUN go mod tidy
RUN go build -o /gateway ./cmd/

FROM alpine:latest
RUN adduser -D -g '' container
USER container
COPY --from=builder /gateway /gateway
ENTRYPOINT ["/gateway"]
